<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>aspnet-KindLink-4cdc40b6-57a7-4876-b374-0c16d3997fc9</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <None Update="app.db" CopyToOutputDirectory="PreserveNewest" ExcludeFromSingleFile="true"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="9.0.15"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.15"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="9.0.15"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.15"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.16" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.15"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Pages\" />
      <Folder Include="wwwroot\images\" />
    </ItemGroup>

</Project>
